version: "3.9"

services:

  mongodb:
    image: mongo
    container_name: database
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - app-network

  backend:
    build: ./server
    container_name: backend
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app
    environment:
      - MONGO_URL=mongodb://mongodb:27017/ranting_car
      - JWT_TOKEN="1234hello"
    depends_on:
      - mongodb
    networks:
      - app-network

  frontend:
    build: ./client
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    environment:
      - REACT_APP_BACKEND_URL=http://127.0.0.1:4000
    depends_on:
      - backend
    networks:
      - app-network

  # nginx:
  #   image: nginx
  #   container_name: nginx-proxy
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  #   links:
  #     - backend
  #     - frontend
  #   depends_on:
  #     - backend
  #     - frontend
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge
