version: "3.9"

services:

  # nginx:
  #   build: nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  # frontend:
  #   build: client
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./client:/app
  #   depends_on:
  #     - backend

  # backend:
  #   build: server
  #   ports:
  #     - "4000:4000"
  #   volumes:
  #     - ./server:/app


#   mysql:
#     image: mysql
#     ports:
#       - "3306:3306"
#     volumes:
#       - ./data:/data/db

# volumes:
#   mysql-data:
