version: "3.9"

services:
  mongodb:
    image: mongo
    container_name: database
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=ranting_car
    volumes:
      - ./data:/data/db
    networks:
      - app-network

  backend:
    build: ./server
    container_name: backend
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app
    environment:
      - DB_USR=admin
      - DB_PASS=password
      - DB_SERVER=mongodb
      - DB_NAME=ranting_car
      - JWT_TOKEN=1234hello
    depends_on:
      - mongodb
    networks:
      - app-network

  frontend:
    build: ./client
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    environment:
      - REACT_APP_BACKEND_URL=http://127.0.0.1:4000
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
